name: Update prebuilt blobs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 1"

jobs:
  update:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - module: "Galaxy A26 (a26xxx)"
            path: "prebuilts/samsung/a26xxx"
          - module: "Galaxy A73 (a73xqxx)"
            path: "prebuilts/samsung/a73xqxx"
          - module: "Galaxy S22 Ultra (b0sxxx)"
            path: "prebuilts/samsung/b0sxxx"
          - module: "Galaxy Flip 6 (b6qxxx)"
            path: "prebuilts/samsung/b6qxxx"
          - module: "Galaxy S23 Ultra (dm3qxxx)"
            path: "prebuilts/samsung/dm3qxxx"
          - module: "Galaxy S24 (e1sxxx)"
            path: "prebuilts/samsung/e1sxxx"
          - module: "Galaxy S24+ (e2sxxx)"
            path: "prebuilts/samsung/e2sxxx"
          - module: "Galaxy Tab S10 FE (gts10fewifixx)"
            path: "prebuilts/samsung/gts10fewifixx"
          - module: "Galaxy S21 Ultra (p3sxxx)"
            path: "prebuilts/samsung/p3sxxx"
          - module: "Galaxy S25 Ultra (pa3qxxx)"
            path: "prebuilts/samsung/pa3qxxx"
          - module: "Galaxy S25 Ultra (China) (pa3qzcx)"
            path: "prebuilts/samsung/pa3qzcx"
          - module: "Galaxy S24 FE (r12sxxx)"
            path: "prebuilts/samsung/r12sxxx"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Free disk space (1/3)
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a

      - name: Free disk space (2/3)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

      - name: Free disk space (3/3)
        uses: rokibhasansagar/slimhub_actions@main
        with:
          retain: 'compiler_cmake'

      - name: Set up build environment
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
            attr ccache clang ffmpeg golang \
            libbrotli-dev libgtest-dev libprotobuf-dev libunwind-dev libpcre2-dev \
            libzstd-dev linux-modules-extra-$(uname -r) lld protobuf-compiler webp
          sudo modprobe erofs f2fs
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Build dependencies
        run: source ./buildenv.sh z3s

      - name: Update prebuilt blobs
        run: |
          source ./buildenv.sh z3s
          ./scripts/internal/update_prebuilt_blobs.sh ${{ matrix.path }}
          echo "PDA_BUILD=$(cat ./${{ matrix.path }}/.current | cut -d "/" -f 1)" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: |
            ${{ matrix.path }}
          commit-message: '${{ matrix.path }}: update blobs to ${{ env.PDA_BUILD }}'
          committer: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          branch: '${{ matrix.path }}'
          delete-branch: true
          title: 'Update ${{ matrix.path }} blobs to ${{ env.PDA_BUILD }}'
          body: ''
